name: "hikari"
description: "Fluid, responsive blog theme for Jekyll"

baseurl: /
url: http://m3xm.github.io/hikari-for-Jekyll

paginate: 10

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true
